libmbim-glib,message: fix build with -Wcast-align in ARM
  mbim-message.c: In function '_mbim_struct_builder_complete':
  mbim-message.c:534:24: error: cast increases required alignment of target type [-Werror=cast-align]
           offset_value = (guint32 *) &(builder->fixed_buffer->data[offset_offset]);
                        ^

(cherry picked from commit 2374eeabf2f163fba3f9680a3e95ddeef8bb8a2e)